#pragma once

enum EMenuStartupState
{
    EMENUPHASE_NONE = 0,
    EMENUPHASE_LANGUAGE_SELECTION = 1,
    EMENUPHASE_PRESS_START = 2,
    EMENUPHASE_SIGN_IN = 3,
    EMENUPHASE_PROMPT_STORAGE_DEVICE = 4,
    EMENUPHASE_WAIT_FOR_STORAGE_DEVICE = 5,
    EMENUPHASE_LOAD_SAVEGAME = 6,
    EMENUPHASE_SAVEGAME_WARNING = 7,
    EMENUPHASE_SCREEN_RESIZE = 8,
    EMENUPHASE_PRE_FADE_INTRO_MOVIE = 9,
    EMENUPHASE_POST_FADE_INTRO_MOVIE = 10,
    EMENUPHASE_INTRO_MOVIE = 11,
    EMENUPHASE_WAIT_FOR_BENCHMARK_RESULTS = 12,
    EMENUPHASE_MAIN_MENU = 13,
    EMENUPHASE_WAIT_FOR_DIALOG = 14,
    EMENUPHASE_WAIT_FOR_ASYNC_SAVE = 15
};
