#pragma once

enum EResourceStatus
{
	RESOURCE_STATUS_UNKNOWN = 0,
	RESOURCE_STATUS_LOADING = 1,
	RESOURCE_STATUS_INSTALLING = 2,
	RESOURCE_STATUS_FAILED = 3,
	RESOURCE_STATUS_VALID = 4,
	RESOURCE_STATUS_HEADER_LOADED = 5
};
