#pragma once

enum ERenderResourceMipInterpolation
{
	eRENDER_RESOURCE_MIP_INTERPOLATION_NONE = 0,
	eRENDER_RESOURCE_MIP_INTERPOLATION_POINT = 1,
	eRENDER_RESOURCE_MIP_INTERPOLATION_LINEAR = 2,
	eRENDER_RESOURCE_MIP_INTERPOLATION_COUNT = 3
};
