#pragma once

enum ECrossHairType
{
	CROSSHAIR_NONE = 0,
	CROSSHAIR_PISTOL = 1,
	CROSSHAIR_REVOLVER = 2,
	CROSSHAIR_SMG = 3,
	CROSSHAIR_RIFLE = 4,
	CROSSHAIR_SHOTGUN = 5,
	CROSSHAIR_SNIPER = 6,
	CROSSHAIR_HARDBALLER = 7,
	CROSSHAIR_UNAIMED = 8
};
