#pragma once

enum EHUDFadeReason
{
	HUD_FADE_REASON_DIFFICULTY = 0,
	HUD_FADE_REASON_FADER = 1,
	HUD_FADE_REASON_TUTORIAL = 2,
	HUD_FADE_REASON_HINTMESSAGE = 3,
	HUD_FADE_REASON_CODE_GENERAL = 4,
	HUD_FADE_REASON_CUTSCENE = 5,
	HUD_FADE_REASON_NUM = 6
};
