#pragma once

enum EHUDItem
{
	HUD_ITEM_TRESPASSING_ICON = 0,
	HUD_ITEM_BEING_WATCHED_ICON = 1,
	HUD_ITEM_AI_STATE_ICON = 2,
	HUD_ITEM_CLOSE_COMBAT = 3,
	HUD_ITEM_CLOSE_COMBAT_RESULT = 4,
	HUD_ITEM_WEAPON_SELECTION = 5,
	HUD_ITEM_WEAPON_DISPLAY = 6,
	HUD_ITEM_THREAT_RADAR = 7,
	HUD_ITEM_SHOW_THREATS = 8,
	HUD_ITEM_FOCUS_BAR = 9,
	HUD_ITEM_BOSS_HEALTHBAR = 10,
	HUD_ITEM_DARE_TIMER = 11,
	HUD_ITEM_PROFILE_DATA = 12,
	HUD_ITEM_DEBUGLOG = 13,
	HUD_ITEM_NUM = 14
};
